export const pokemons = [
    {
        id: 1,
        number: 25,
        name: "Pikachu",
        classification: "Mouse Pokémon",
        fleeRate: 0.1,
    },
    {
        id: 2,
        number: 4,
        name: "Charmander",
        classification: "Lizard Pokémon",
        fleeRate: 0.15,
    },
    {
        id: 3,
        number: 7,
        name: "Squirtle",
        classification: "Tiny Turtle Pokémon",
        fleeRate: 0.12,
    },
    {
        id: 4,
        number: 1,
        name: "Bulbasaur",
        classification: "Seed Pokémon",
        fleeRate: 0.1,
    },
    {
        id: 5,
        number: 16,
        name: "Pidgey",
        classification: "Tiny Bird Pokémon",
        fleeRate: 0.2,
    },
    {
        id: 6,
        number: 10,
        name: "Caterpie",
        classification: "Worm Pokémon",
        fleeRate: 0.18,
    },
    {
        id: 7,
        number: 19,
        name: "Rattata",
        classification: "Mouse Pokémon",
        fleeRate: 0.15,
    },
    {
        id: 8,
        number: 13,
        name: "Weedle",
        classification: "Hairy Bug Pokémon",
        fleeRate: 0.2,
    },
    {
        id: 9,
        number: 22,
        name: "Fearow",
        classification: "Beak Pokémon",
        fleeRate: 0.17,
    },
    {
        id: 10,
        number: 109,
        name: "Koffing",
        classification: "Poison Gas Pokémon",
        fleeRate: 0.1,
    },
    {
        id: 11,
        number: 58,
        name: "Growlithe",
        classification: "Puppy Pokémon",
        fleeRate: 0.15,
    },
    {
        id: 12,
        number: 74,
        name: "Geodude",
        classification: "Rock Pokémon",
        fleeRate: 0.12,
    },
    {
        id: 13,
        number: 95,
        name: "Onix",
        classification: "Rock Snake Pokémon",
        fleeRate: 0.08,
    },
    {
        id: 14,
        number: 37,
        name: "Vulpix",
        classification: "Fox Pokémon",
        fleeRate: 0.12,
    },
    {
        id: 15,
        number: 133,
        name: "Eevee",
        classification: "Evolution Pokémon",
        fleeRate: 0.1,
    },
    {
        id: 16,
        number: 147,
        name: "Dratini",
        classification: "Dragon Pokémon",
        fleeRate: 0.1,
    },
    {
        id: 17,
        number: 92,
        name: "Gastly",
        classification: "Gas Pokémon",
        fleeRate: 0.15,
    },
    {
        id: 18,
        number: 50,
        name: "Diglett",
        classification: "Mole Pokémon",
        fleeRate: 0.2,
    },
    {
        id: 19,
        number: 27,
        name: "Sandshrew",
        classification: "Mouse Pokémon",
        fleeRate: 0.18,
    },
    {
        id: 20,
        number: 143,
        name: "Snorlax",
        classification: "Sleeping Pokémon",
        fleeRate: 0.05,
    },
];